import type { Metadata } from "next";
import { Montserrat, Noto_Sans } from "next/font/google";
import "./globals.css";
import { Header } from "@/components/header";
import Footer from "@/components/footer";
import { PhotoProvider } from "@/context/contextImage";

const notoSans = Noto_Sans({
  weight: ["400", "500", "700"],
  style: ["normal"],
  subsets: ["latin"],
  variable: "--font-noto-sans",
});

const montserrat = Montserrat({
  weight: ["400", "500", "700"],
  style: ["normal"],
  subsets: ["latin"],
  variable: "--font-montserrat",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${notoSans.variable} ${montserrat.variable} font-main flex flex-col items-center justify-center min-h-screen gap-4 sm:gap-8 p-2`}
      >
        <PhotoProvider>
          <Header />
          <div className="container flex-1 flex flex-col">{children}</div>
          <Footer />
        </PhotoProvider>
      </body>
    </html>
  );
}
